### ISSUE TITLE
Error when using version 2.2.0 on Eco server 0.9.2.4

### ISSUE THREAD

**Issue by iShotFT** [Eco-DiscordLink/EcoDiscordPlugin#38]
```System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'DSharpPlus.CommandsNext, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Eco.ModKit.ModKitPlugin.LoadModDlls()
   at Eco.ModKit.ModKitPlugin.LoadModsData(TaskCompletionSource`1 done)
   at Eco.ModKit.ModKitPlugin..ctor(TaskCompletionSource`1 done)
System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus.CommandsNext, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus.CommandsNext, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
File name: 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Eco.ModKit.ModKitPlugin.AppDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)


Outer Exceptions:
Exception has been thrown by the target of an invocation.
 
[02:11:57.583] [1] [Error] [Eco] Unhandled errorSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Eco.Server.PluginManager.AddPlugin(Type pluginType, Object[] p)
   at Eco.Server.PluginManager.AddPlugin[T](Object[] p)
   at Eco.Server.PluginManager.AddPluginsAsync(StartupInfo startupInfo)
   at Eco.Server.PluginManager.PostCreateAsync(StartupInfo startupInfo)
   at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
   at Eco.Server.ApplicationHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Eco.Server.MainClass.Main(String[] args)
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'DSharpPlus.CommandsNext, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
Could not load file or assembly 'DSharpPlus, Version=4.0.0.711, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Eco.ModKit.ModKitPlugin.LoadModDlls()
   at Eco.ModKit.ModKitPlugin.LoadModsData(TaskCompletionSource`1 done)
   at Eco.ModKit.ModKitPlugin..ctor(TaskCompletionSource`1 done)```

**Comment by iShotFT** [comment]
Fixed when removing previous .dll's (I think an upgrade guide would be a great thing to add to this)

**Comment by MonzUn** [comment]
Hey! It seems to be missing basically all of the dependencies.
What environment are you using (dedicated or hosted, OS etc)?
What does your file structure look like? Did you use the same structure as in the .zip file?

**Comment by MonzUn** [comment]
> Fixed when removing previous .dll's (I think an upgrade guide would be a great thing to add to this)

Hmm, how do you mean?
There should only be 1 dll extra after an overwrite and that one just doesn't do anything so I never told people to remove it.

**Comment by iShotFT** [comment]
> > Fixed when removing previous .dll's (I think an upgrade guide would be a great thing to add to this)
> 
> Hmm, how do you mean?
> There should only be 1 dll extra after an overwrite and that one just doesn't do anything so I never told people to remove it.

I came from version 2.0.1 which had .dll's in the main folder instead of a separate folder in the Mods directory

**Comment by MonzUn** [comment]
Ah. 2.0.1 -> 2.2.0 is not a supported update path.
Those changes were documented in a previous update step in the changelog.

I didn't even know 2.0.1 still worked with Eco 9.2.X.
