### ISSUE TITLE
Issue with /dl-link Discord Account - Unauthorized

### ISSUE THREAD

**Issue by Alteraner** [Eco-DiscordLink/EcoDiscordPlugin#51]
Hello,
 I have the below issue with the `/dl-link` command. In Server Log you can see the following issue. The bot seems to not have enough permission to do so. I have given him Admin permissions on Discord but he still gets this error. Please can you help, what needs to be set up or is it a bug which needs to be fixed.
 Thanks.

` [10:32:39] [DiscordLink] ERROR: Error occured when attempting to fetch all guild members. Error message: DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403
   at DSharpPlus.Net.DiscordApiClient.ListGuildMembersAsync(UInt64 guild_id, Nullable`1 limit, Nullable`1 after)
   at DSharpPlus.Entities.DiscordGuild.GetAllMembersAsync()
   at Eco.Plugins.DiscordLink.Utilities.DiscordUtil.GetGuildMembersAsync(DiscordGuild guild)`

**Comment by Alteraner** [comment]
I found out what permissions  need to be set. On Bot Page you need to enable below permission:
![image](https://user-images.githubusercontent.com/47274045/117669993-c8b6a580-b1a7-11eb-9cfb-988eb27b497c.png)

Issue can be closed.
