### ISSUE TITLE
Error: Cannot bind to the target method because its signature is not compatible with that of the delegate type.

### ISSUE THREAD

**Issue by DrunkMunki** [Eco-DiscordLink/EcoDiscordPlugin#60]
I reinstalled ECO
downloaded the new version of DiscordLink 2.2.2
Crashes.. if i remove the DiscordLink mod, it loads fine.
Below is the error:

```
[19:21:44.594] [5] [ Info] [Eco] Server Initialization... Finished in 85,206.1ms
 
[19:21:44.618] [24] [Error] [Eco] Failed to start the server. Exception was Exception: ArgumentException
Message:Cannot bind to the target method because its signature is not compatible with that of the delegate type.
Source:System.Private.CoreLib

System.ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.ReplaceCommandProcessor()
   at Eco.Gameplay.Systems.Chat.ChatCommandService..ctor()
   at Eco.Gameplay.Systems.Chat.ChatManager..ctor()
   at Eco.Gameplay.Systems.Chat.ChatServer..ctor()
Outer Exceptions:
Exception has been thrown by the target of an invocation.
 
[19:21:49.654] [24] [ Info] [Eco] Shutdown finished
```

**Comment by Teax20** [comment]
Greetings, received the same error, not only with DiscordLink. 
The problem is the EM Framework. Many mods relate to this framework and it is broken due to the 9.4 update.

Best regards :)

**Comment by DrunkMunki** [comment]
Ahh i see on https://elixrmods.com/mods/elixr-mods

Current Supported Eco Version: 9.3.x

so this mod wont work until the Elixr mod is updated.

**Comment by MonzUn** [comment]
EM is broken because SLG needs to hot fix Eco for it to work. So we are waiting for the devs to release a hotfix.
