### ISSUE TITLE
Possible issue with new wave emote

### ISSUE THREAD

**Issue by kotoroshinoto** [Eco-DiscordLink/EcoDiscordPlugin#63]
I am not certain whether discordlink is at fault, but after the new update, things are crashing relating to chat behavior and the word "wave" somehow. 

[12:42:05] Failed to start the server. Exception was Exception: ArgumentException
Message:An item with the same key has already been added. Key: wave
Source:System.Private.CoreLib

System.ArgumentException: An item with the same key has already been added. Key: wave
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.AddTypeCommands(Type handlerType, Dictionary`2 englishCommands, List`1 subCommands)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.AddCommandHandlers(IEnumerable`1 handlerTypes)
   at Eco.Gameplay.Systems.Chat.ChatCommandService.AddHandlersByReflection()
   at Eco.Gameplay.Systems.Chat.ChatCommandService..ctor()
   at Eco.Gameplay.Systems.Chat.ChatManager..ctor()
   at Eco.Gameplay.Systems.Chat.ChatServer..ctor()
Outer Exceptions:
Exception has been thrown by the target of an invocation.

**Comment by kotoroshinoto** [comment]
It was the EM mods that did it, sorry for bothering you.
