### ISSUE TITLE
NullReferenceException when using /dl-link

### ISSUE THREAD

**Issue by Pasukaru** [Eco-DiscordLink/EcoDiscordPlugin#77]
```
Eco 0.9.6
EM  3.3.0
DL  3.1.0
```
```
[2022-09-01 02:06:10.166][Error] An exception occured while attempting to execute a command.
Command name: "<LinkDiscordAccount>b__0"
Calling user: "Pasukaru"
Error message: System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.DiscordLink.EcoCommands.<>c__DisplayClass41_0.<LinkDiscordAccount>b__0(User lUser, String[] args)
   at Eco.Plugins.DiscordLink.EcoCommands.ExecuteCommand[TRet](EcoCommand command, User callingUser, String[] parameters)
```
I did not get a DM from the bot.

Running `/dl-link Pasukaru` a second time tells me that the account is already linked. But the role assignments etc do not work.

Everything else seems to work. Duplex chat, server status etc works fine.

All troubleshooting commands are successful.
I also tried clearing world data and persistent data, same result.

**Comment by MonzUn** [comment]
The issue was with DL not checking for DM permissions and you likely having prohibited DMs. It's been resolved and will be in an upcoming patch.
